name: Oratio
options:
  bundleIdPrefix: ing.unlimit
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  grpc-swift:
    url: https://github.com/grpc/grpc-swift
    from: "1.24.2"
  swift-protobuf:
    url: https://github.com/apple/swift-protobuf
    from: "1.28.0"

targets:
  Oratio:
    type: application
    platform: macOS
    sources:
      - path: Oratio
        excludes:
          - "**/*.entitlements"
    resources:
      - path: Oratio/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ing.unlimit.oratio
        PRODUCT_NAME: Oratio
        INFOPLIST_FILE: Oratio/Info.plist
        CODE_SIGN_ENTITLEMENTS: Oratio/Oratio.entitlements
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: KMDVJDU523
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: "NO"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - sdk: ScreenCaptureKit.framework
      - sdk: Speech.framework
      - sdk: AVFoundation.framework
      - package: grpc-swift
        product: GRPC
      - package: swift-protobuf
        product: SwiftProtobuf
